version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    assignees:
      - 'BGruenberg'
    cooldown:
      default-days: 7
    groups:
      angular-minor:
        patterns:
          - "@angular*"
          - "@ng-bootstrap/ng-bootstrap"
        update-types:
          - "minor"
          - "patch"
      typescript-eslint:
        patterns:
          - "typescript-eslint"
          - "@typescript-eslint/*"
      jest:
        patterns:
          - "jest"
          - "jest-environment-jsdom"

  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: weekly
      day: monday
      time: '09:00'
      timezone: Europe/Berlin

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: weekly
      day: monday
      time: '09:00'
      timezone: Europe/Berlin
