# DO NOT USE IN PRODUCTION

name: terminfinder

services:
  terminfinder:
    build: .
    # uncomment the next two lines to test parametrization. Change environment.js.example to your liking.
    # volumes:
    # - ./environment.js.example:/usr/share/nginx/html/environment.js:ro
    container_name: terminfinder
    hostname: terminfinder
    ports:
      - '8080:8080'
